name: Generate grass

on:
  push:
  schedule:
    - cron: '10 15 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        id: pnpm-setup
        uses: pnpm/action-setup@v4
        continue-on-error: true

      - name: Setup Node.js with pnpm cache
        if: steps.pnpm-setup.outcome == 'success'
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Setup Node.js with npm cache (fallback)
        if: steps.pnpm-setup.outcome == 'failure'
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install pnpm globally (fallback)
        if: steps.pnpm-setup.outcome == 'failure'
        run: npm install -g pnpm

      - name: Install dependencies with pnpm
        if: steps.pnpm-setup.outcome == 'success'
        run: pnpm install --frozen-lockfile

      - name: Install dependencies with pnpm (fallback)
        if: steps.pnpm-setup.outcome == 'failure'
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm build

      - name: Generate grass
        run: pnpm generate -- --animated --color red
        env:
          TOKEN: ${{ secrets.TOKEN }}
          USERNAME: ${{ secrets.USERNAME }}
          
      - name: Commit and Push
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add github-glass.svg
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto update GitHub grass chart [$(date +'%Y-%m-%d %H:%M:%S')]"
            git push
          fi
