name: Generate grass
on:
  push:
  schedule:
    - cron: '10 15 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install svgwrite
          pip install requests
          pip install numpy

      - name: Run script
        run: |
          python generate_grass.py --animated --color red
        env:
          TOKEN: ${{ secrets.TOKEN }}
          USERNAME: ${{ secrets.USERNAME }}
          
      # 以下、ファイルのコミットとプッシュ
      - name: Commit and Push
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "bot"
          git add .
          git commit -m "Auto commit by GitHub Actions" || exit 0 # ignore error
          git push
